spring:
  application:
    name: imedia
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/imedia}
    username: ${DATABASE_USER:imedia}
    password: ${DATABASE_PASSWORD:imedia}
  liquibase:
    enabled: false

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.data.jdbc: DEBUG
    org.springframework.transaction: DEBUG

app:
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecret: ${STRIPE_WEBHOOK_SECRET}